### ISSUE TITLE
Switch to new API (2017–01–17) and SDK (boto3)

### ISSUE THREAD

**Issue by longouyang** [longouyang/cosub#10]

**Comment by nataliavelez** [comment]
I received a notice from the mTurk recently warning that older versions of the API are set to be deprecated on June 1, 2018. Will this affect the latest version of cosub? Thanks!

**Comment by longouyang** [comment]
Yes, I believe this will affect cosub. I recommend switching to [nosub](https://github.com/longouyang/nosub)

**Comment by nataliavelez** [comment]
Got it, thank you!
