### ISSUE TITLE
auto-aggregate into csv instead of individual json

### ISSUE THREAD

**Issue by hawkrobe** [longouyang/cosub#5]

**Comment by longouyang** [comment]
CSV is a bad format for richly structured data, so I'm going to stick with JSON.

**Comment by hawkrobe** [comment]
Sorry, I must have misunderstood. I thought this was the consensus of our lab meeting on web experiment tools: that the output of separate json files per turker was the main reason no one had switched over from submiterator to cosub (even though it's better in every other way)! Maybe I shouldn't have said "auto", and I agree that json is better for richly structured data, but for most applications, the user just wants to import their results into R without having to write a hacky script that loops over file names and sticks them in a data frame. 

There seem to be a few ways of making this improvement without sacrificing the json format, if that's the sticking point, e.g. pulling all participants into one big json that can be read into a data frame, or providing some "reformat" option that extracts the relevant fields and outputs a csv.

**Comment by longouyang** [comment]
FYI, I wasn't at the lab meeting, as I'm no longer officially in the lab.

At this point, I'm unlikely to make any changes to this repo that aren't well suited to my personal use. It sounds like the way to make the changes you've suggested is for there to be a cocolab fork.

**Comment by hawkrobe** [comment]
Ah, gotcha gotcha! Will do.

**Comment by longouyang** [comment]
Alternatively, if you want to submit PRs that add new functionality without sacrificing old (e.g., in this case, adding a csv output option in addition to json), then I'd certainly merge. But going forward, I won't have the bandwidth to personally write new code that isn't directly useful for my own work.

**Comment by hawkrobe** [comment]
That's extremely reasonable :)
