### ISSUE TITLE
automatically reformat and anonymize worker ids

### ISSUE THREAD

**Issue by hawkrobe** [longouyang/cosub#6]

**Comment by longouyang** [comment]
It can be handy to actually know what the worker id is (e.g., for discarding data from repeat workers), so I've decided that cosub itself won't do any anonymizing.

**Comment by hawkrobe** [comment]
Maybe I should've clarified the suggestion better. The lack of an anonymizatiom option caused a huge number of problems in mike's class this year, where students couldn't check their results into github and the teaching team had to write a  hacky bash script that caused more problems -- students who ran multiple hits could no longer identify unique turkers, which we were still trying to debug over the summer! 

I agree that cosub shouldn't throw out worker ids automatically, but would it be so bad to have a flag that hashes the ids and creates an anonymize version of the results? For reproducible analysis pipelines, I think this is a critical step.

**Comment by longouyang** [comment]
> I agree that cosub shouldn't throw out worker ids automatically, but would it be so bad to have a flag that hashes the ids and creates an anonymize version of the results? For reproducible analysis pipelines, I think this is a critical step.

That's sensible. Let's talk on #5 about general strategy for updating cosub.
